[build]
  command = "rm -rf node_modules package-lock.json && npm install && npm install @rollup/rollup-linux-x64-gnu --save-optional && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
